name: E2E Tests with Maestro

on:
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: "temurin"
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Start Android Emulator
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30  # Use API level 30 (Android 11)
          target: google_apis
          arch: x86_64
          profile: pixel_4
          disable-animations: true
          script: echo "Android Emulator is ready"

      # Install Maestro CLI
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # Verify Maestro installation
      - name: Verify Maestro Installation
        run: maestro --version

      # Run E2E tests using Maestro
      - name: Run Maestro Tests
        run: maestro test path/to/your-maestro-tests
