name : Flutter CI Workflow

on :
  push :
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Pub dependencies
        run:  flutter pub get

      - name: Analyze
        run: flutter analyze

      - name : Launch Simulator
        id : sim
        uses: futureware-tech/simulator-action@v4

      - name: Install the application
        run : | 
          flutter run -d ${{steps.sim.outputs.udid}} &
          while ! xcrun simctl get_app_container booted com.example.tutorial2; do
            sleep 5
          done;
  

      - name: Install Meastro

        run: |
          export MAESTRO_VERSION=1.39.9
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin >> $GITHUB_PATH

      - name: Maestro test
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 360000
        run: maestro record maestro/test.yml --local test.mp4

      - name: Upload Test Video
        uses : actions/upload-artifact@v4
        with:
          name: test-video
          path : test.mp4







