name : Flutter CI Workflow

on :
  push :
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter_channel : [stable, beta]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{matrix.flutter_channel}}

      - name: Pub dependencies
        run:  flutter pub get

      - name: Analyze
        run: flutter analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Pub dependencies
        run: flutter pub get

      - name: Formatting
        run: dart format --set-exit-if-changed ./

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy
        run: echo "Deploy"


