name : Flutter CI Workflow

on :
  push :
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: macos-latest
    # strategy:
    #   matrix:
    #     flutter_channel : [stable, beta]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Pub dependencies
        run:  flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Launch iOS Simulator
        uses: futureware-tech/simulator-action@v4
        with:
          device: 'iPhone 15'
          runtime: '18.2'

      - name: Install Maestro
        run: |
          export MAESTRO_VERSION=1.39.9
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Maestro test flow with recording
        run:  maestro record maestro/test.yml --local test.mp4


      - name: Upload Test Video
        uses: actions/upload-artifact@v4
        with:
          name: test-video
          path: test.mp4